DROP USER IF EXISTS c4dev;
CREATE USER c4dev WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;
ALTER USER c4dev WITH PASSWORD 'c4dev!';

DROP DATABASE if exists grafana;
CREATE DATABASE grafana WITH OWNER = postgres TABLESPACE = pg_default CONNECTION LIMIT = -1;